POST https://musical-space-tribble-7697wjv5qj63p4qr-3333.app.github.dev/users HTTP/1.1
Content-Type: application/json

{
  "name": "John Edson",
  "email": "john@example.com"
}

####

PUT https://musical-space-tribble-7697wjv5qj63p4qr-3333.app.github.dev/users/4 HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe Leticia",
  "email": "john@example.com"
}

####

DELETE https://musical-space-tribble-7697wjv5qj63p4qr-3333.app.github.dev/users/4 HTTP/1.1